Make the footer like figma file
OWASP-BLT/BLT pull request #1016
Opened 2023-01-12 14:31 UTC by Bhawna1203

- Solved issue #1009
- Changed Footer's logo and background color as per the figma file.
![Screenshot from 2023-01-12 20-01-21](https://user-images.githubusercontent.com/81790585/212093796-09b1976f-0da2-4a90-a77c-31cee42801bb.png)

2023-01-13 06:03 UTC, fredfalcon approved these changes

2023-01-16 12:50 UTC, fredfalcon requested changes
Tests are not passing

2023-01-22 06:04 UTC, AtmegaBuzz commented
Hey @Bhawna1203 can you pull the latest merges. it will rerun the tests

2023-01-22 06:30 UTC, fredfalcon approved these changes

2023-01-22 06:30 UTC, merged