Append multiple screenshot in issue json
OWASP-BLT/BLT pull request #1078
Opened 2023-02-22 05:47 UTC by Kej-r03

Fixes #1075

2023-02-22 05:57 UTC, fredfalcon requested changes
This works however I think it will be good to have all screenshots attached. Thanks

2023-02-22 06:09 UTC, Kej-r03 commented
I have attached a screen recording of the working. You can see that we do not get any console errors. Thanks

https://user-images.githubusercontent.com/99071926/220536801-4e4dedde-349b-42c8-8a0d-ef427b29ce47.mp4

2023-02-23 16:00 UTC, fredfalcon requested changes
Can you please make it attach all screenshots to GitHub?

2023-02-23 18:08 UTC, fredfalcon requested changes
You should be able to use the IssueScreenshot.image.url function to get the url - Django has a built in image url function.

2023-02-23 18:23 UTC, Kej-r03 commented
Ok, I think the first commit was better itself, so I have reverted back. I have created an issue using the github api post method [here](https://github.com/Kej-r03/Practice3/issues/15). Here too the image is not fully loaded though

2023-02-23 18:28 UTC, fredfalcon requested changes
add string to first loop

2023-02-23 18:52 UTC, Kej-r03 commented on website/views.py
> +            screenshot_text += "![0](" + screenshot.image.url + ") "
Yes, I have tried this and this gave an error 'ImageFileDescriptor' object has no attribute 'url'. [my previous comment on this](https://github.com/OWASP/BLT/issues/1075#issuecomment-1439479230)

2023-02-23 19:12 UTC, fredfalcon approved these changes

2023-02-23 19:18 UTC, merged