Created a method to hide image from public when issue is hidden
OWASP-BLT/BLT pull request #1130
Opened 2023-03-11 15:56 UTC by pranav-iitr

fix #1104

2023-03-12 15:50 UTC, pranav-iitr commented
@fredfalcon pls, review the changes

2023-03-12 17:56 UTC, fredfalcon requested changes
Can you please setup a test to make sure this works?

2023-03-15 04:36 UTC, fredfalcon requested changes
Please add a test

2023-03-15 04:47 UTC, pranav-iitr commented
> Please add a test

is a test evolving only models is sufficient or a selenium based test is required?

2023-03-16 08:30 UTC, pranav-iitr commented
@fredfalcon  pls check

2023-03-16 08:58 UTC, pranav-iitr commented
made the changes pls check

2023-03-17 10:16 UTC, pranav-iitr commented
> The last 6 lines of the test can be rewritten to assert true (file exists)

Made the changes please check

2023-03-22 10:29 UTC, pranav-iitr commented
> Please add a test

made changes pls check

2023-03-24 03:43 UTC, pranav-iitr commented
> > Please add a test
> 
> made changes pls check

@fredfalcon

2023-03-24 04:11 UTC, fredfalcon requested changes
Please take out the try / except and unchange any code not related to the change

2023-03-24 04:32 UTC, pranav-iitr commented on website/models.py
> +    blob = go
removed this bug

2023-03-24 04:33 UTC, pranav-iitr commented
> Please take out the try / except and unchange any code not related to the change

rectified

2023-03-24 04:39 UTC, fredfalcon requested changes
Please remove the field and clean up any unused print or code

2023-03-24 05:31 UTC, pranav-iitr commented on website/models.py
> +    # blob = go
removed pls check

2023-03-24 05:31 UTC, pranav-iitr commented on website/migrations/0073_issuescreenshot_hide.py
> +# Generated by Django 4.1 on 2023-03-11 13:42
removed pls check

2023-03-24 13:27 UTC, fredfalcon requested changes
Please see inline

2023-03-25 08:35 UTC, pranav-iitr commented on website/tests.py
> +                self.assertTrue(False, "files exist")
resolved pls check

2023-03-25 08:35 UTC, pranav-iitr commented on website/models.py
> +
resolved

2023-03-25 08:35 UTC, pranav-iitr commented on website/models.py
> +
resoloved

2023-03-25 08:35 UTC, pranav-iitr commented on website/models.py
> +                    # if not settings.DEBUG:
resoloved

2023-03-25 08:36 UTC, pranav-iitr commented on website/tests.py
> +        print(sys.path)
resolved

2023-03-25 08:36 UTC, pranav-iitr commented on website/tests.py
> +        self.selenium.find_element(
resolved

2023-03-25 08:39 UTC, fredfalcon submitted a review, later dismissed
Looking better.  Can you please remove any changes that are not directly related to your change? Because it will make it easier to review.

2023-03-25 08:40 UTC, pranav-iitr commented
> Looking better. Can you please remove any changes that are not directly related to your change? Because it will make it easier to review.

have removed

2023-03-25 08:45 UTC, pranav-iitr commented
> Looking better. Can you please remove any changes that are not directly related to your change? Because it will make it easier to review.

removed @fredfalcon  pls check

2023-03-25 19:29 UTC, AtmegaBuzz commented
LGTM! @fredfalcon

2023-03-27 05:33 UTC, pranav-iitr commented
@fredfalcon pls merge if everything is fine

2023-03-27 14:14 UTC, fredfalcon approved these changes

2023-03-27 14:19 UTC, merged