Feature: Revamp Report a bug page with recaptcha and private bug reporting
OWASP-BLT/BLT pull request #1240
Opened 2023-05-07 19:57 UTC by AtmegaBuzz

Start Bughunt page with private bug hunting #1229

![image](https://user-images.githubusercontent.com/68425016/236699963-afe4f7a1-aa16-4bd2-9772-707f171d511e.png)

2023-05-08 22:21 UTC, DonnieBLT requested changes
Why do we need a recpacha, the simple captcha is working fine?  Also my main issue with this new design is that it's too large for the screen - can you make everything fit on one page above the fold?

2023-05-09 02:39 UTC, AtmegaBuzz commented
Simple captcha is bit annoying, you have to enter every time but recaptcha it just easy for users, just one tick and done if bot comes the puzzle will be asked.
Ok got it I'll fit it in one page, will move the editor to right and other things to left.

2023-05-09 16:34 UTC, DonnieBLT commented
Can you show the full screenshot with the browser as well?  It looks good but maybe it could be a bit smaller all around

2023-05-10 01:57 UTC, AtmegaBuzz commented
OK I'll add the suggestions, for preview I'll add a pop up when we click on the image box in red color it will show the preview and about mobile screem I will just flex wrap it, just to be sure that desktop screen looks good before moving

2023-05-13 04:47 UTC, AtmegaBuzz commented
![image](https://github.com/OWASP/BLT/assets/68425016/a6a631d6-2e4d-4941-a45d-c5b3f3909383)
![image](https://github.com/OWASP/BLT/assets/68425016/2046b487-ad36-4005-9eb4-c91cd8543f9d)
![image](https://github.com/OWASP/BLT/assets/68425016/82d65c6d-c58b-4bf8-8c9c-02a8aedd43e1)
![image](https://github.com/OWASP/BLT/assets/68425016/cbef7851-a2c4-4aa4-87de-e53dac69d6bd)
![image](https://github.com/OWASP/BLT/assets/68425016/ac6dbbe8-3051-4be0-8f59-56b78c2dd317)
![image](https://github.com/OWASP/BLT/assets/68425016/551b344d-57df-4299-94a1-69140de6b6fd)

@DonnieBLT @just-ary27 I've added responsiveness, for more detail view you can see the video shared on slack.

2023-05-17 18:22 UTC, DonnieBLT requested changes
a few changes requested

2023-05-17 18:22 UTC, DonnieBLT commented on blt/urls.py
> +    re_path(r"^report/$", IssueCreate.as_view(), name="report"),
can we leave issue/ as there may be previous links to it - like the extension

2023-05-17 18:22 UTC, DonnieBLT commented on website/alternative_views.py
> +                "body": screenshot_text +
add description_text here

2023-05-17 18:22 UTC, DonnieBLT commented on website/models.py
> -        domain = parsed_url.hostname
curious as to why this was changed?

2023-05-17 18:22 UTC, DonnieBLT commented on website/static/css/navbar.css
> -}
remove unchanged

2023-05-17 18:22 UTC, DonnieBLT commented on blt/urls.py
> +    # path("captcha/", include("captcha.urls")),
please keep the existing captcha code so the existing report an issue page can continue to work

2023-05-17 19:09 UTC, DonnieBLT requested changes

2023-05-17 19:09 UTC, DonnieBLT commented on blt/urls.py
> +    # path("captcha/", include("captcha.urls")),
@AtmegaBuzz please revert this line

2023-05-17 19:09 UTC, DonnieBLT commented on blt/urls.py
> -    re_path(r"^report/$", IssueCreate.as_view()),
@AtmegaBuzz please add this back

2023-05-17 19:09 UTC, DonnieBLT commented on website/models.py
> -    captcha = CaptchaField()
@AtmegaBuzz please add this back

2023-05-17 19:09 UTC, DonnieBLT commented on website/models.py
> -        domain = parsed_url.hostname
@AtmegaBuzz can you comment on why this changed?

2023-05-17 20:46 UTC, DonnieBLT requested changes
a bit more detailed feedback

2023-05-17 20:46 UTC, DonnieBLT commented on website/models.py
> -        domain = parsed_url.hostname
@AtmegaBuzz this is meant to extract the domain name from the url that was reported, it looks like it was operating correctly.  Can you please revert this?  If there is a specific case where it has to change, can you please add an automated test to show that it's working as intended?

2023-05-17 20:46 UTC, DonnieBLT commented on poetry.lock
Can undo all changes to the poetry files

2023-05-17 20:46 UTC, DonnieBLT commented on blt/settings.py
> +    'captcha',
can revert this to double quotes

2023-05-17 20:46 UTC, DonnieBLT commented on pyproject.toml
can undo this change

2023-05-17 20:46 UTC, DonnieBLT commented on website/models.py
> -from decimal import Decimal
swap this back

2023-05-17 20:46 UTC, DonnieBLT commented on website/static/css/navbar.css
> +}
remove blank change

2023-05-17 20:46 UTC, DonnieBLT commented on website/templates/500.html
> -                var redirect_url = 'https://{% env "FQDN" %}/report/?url=' + url;
/issue/ is used for the issue - can revert this

2023-05-17 20:46 UTC, DonnieBLT commented on website/templates/includes/footer.html
> +<footer class="bg-black text-white pt-12 pb-8 px-12 relative ">
what does this do? is it related to the add a new issue page?

2023-05-17 20:46 UTC, DonnieBLT commented on website/templates/includes/navbar.html
> -                        <a href="/report">
revert this

2023-05-17 20:46 UTC, DonnieBLT commented on website/templates/includes/navbar.html
> -                <a href="/report/" class="nav-hidden lg:!inline-block bg-red-500 hover:bg-red-600 h-[38px] py-[8px] px-[25px] whitespace-nowrap text-2xl font-bold text-white leading-[21px] cursor-poi
revert

2023-05-17 20:46 UTC, DonnieBLT commented on website/templates/report.html
> +                    {% comment %} <button class="btn btn-primary btn-block"
save this for a different PR

2023-05-17 20:46 UTC, DonnieBLT commented on website/tests.py
> +        self.selenium.get('%s%s' % (self.live_server_url, '/issue/'))
revert

2023-05-17 20:46 UTC, DonnieBLT commented on website/views.py
> +        clean_domain = self.request.POST["url"].replace("www.", "").replace("https://","").replace("http://","")
revert

2023-05-17 20:46 UTC, DonnieBLT commented on website/views.py
> +        redirect_url = "/issue"
revert

2023-05-19 15:33 UTC, DonnieBLT requested changes

2023-05-19 15:33 UTC, DonnieBLT commented on website/models.py
> -        domain = parsed_url.hostname
@AtmegaBuzz please revert this unless you add a test to make sure it works

2023-05-19 15:33 UTC, DonnieBLT commented on website/static/css/navbar.css
> +}
still seeing a "no change" change here...

2023-05-19 15:33 UTC, DonnieBLT commented on website/templates/includes/footer.html
> +<footer class="bg-black text-white pt-12 pb-8 px-12 relative ">
@AtmegaBuzz what does this do?  Is it needed for the add a new issue page?  Please revert it if not - would like a minimal amount of changes files

2023-05-19 15:33 UTC, DonnieBLT commented on website/templates/report.html
> +                    <button class="btn btn-primary btn-block"
what does this change do, can you revert it?

2023-05-20 12:58 UTC, closed without merging