Issue #828
OWASP-BLT/BLT pull request #1437
Opened 2023-09-25 19:55 UTC by JisanAR03

i make this PR again after target the correct file ,i'm very sry for my previous mistake

BLT use for translate language : i18n, i just make some changes on template i mean just rewrite some text with "{% trans '' %}" and also i did some changes on locale folder because i had translate some text manually because they are translate automatically .
I attach some image of before and after :
before:
       
![image](https://github.com/OWASP/BLT/assets/97744811/dd911187-181d-45d8-9a6c-cf4400f3b325)

after :

    
![image](https://github.com/OWASP/BLT/assets/97744811/675692b2-6a1f-4755-9ef0-6ec637f89536)

i fix all page like this for each language.

2023-09-29 07:39 UTC, AtmegaBuzz commented
LGTM @DonnieBLT

2023-10-06 00:54 UTC, DonnieBLT requested changes
a couple of tweaks

2023-10-06 00:54 UTC, DonnieBLT commented on website/templates/hunt.html
> +                        <option value="Flea">Flea Plan $9.00 / {% trans 'Month' %}</option>
can add trans to these too

2023-10-06 00:54 UTC, DonnieBLT commented on website/templates/index.html
> +        <h1 class="page-sub-header">Bugheist is 100% {% trans "free to use" %}, {% trans "Open Source and a non-commercials" %}, {% trans "not for profit initiative" %}.</h1>
non-commercial

2023-10-06 00:54 UTC, DonnieBLT commented on website/templates/mobile_about.html
> +<h2>Bugheist is 100% {% trans 'free to use' %}, {% trans 'Open Source and a non-commercials' %}, {% trans 'not for profit initiative' %}.
```suggestion
<h2>{% env 'PROJECT_NAME' %} is 100% {% trans 'free to use' %}, {% trans 'Open Source and a non-commercials' %}, {% trans 'not for profit initiative' %}. 
```

2023-10-06 01:32 UTC, JisanAR03 commented
@DonnieBLT  I will make PR again after update the code,, thanks for the review sir

2023-10-06 02:34 UTC, DonnieBLT commented on website/templates/hunt.html
> +                        <option value="Flea">Flea Plan $9.00 / {% trans 'Month' %}</option>
I mean like {% trans "Ant plan" %}

2023-10-06 02:35 UTC, DonnieBLT requested changes

2023-10-06 02:35 UTC, DonnieBLT commented on website/templates/hunt.html
> +<h1 class="page-sub-header">Bugheist is 100% {% trans 'free to use' %}, {% trans 'Open Source and a non-commercial' %}, {% trans 'not for profit initiative' %}.</h1>
Replace with project_name tag

2023-10-06 02:54 UTC, JisanAR03 commented on website/templates/hunt.html
> +<h1 class="page-sub-header">Bugheist is 100% {% trans 'free to use' %}, {% trans 'Open Source and a non-commercial' %}, {% trans 'not for profit initiative' %}.</h1>
completed sir

2023-10-06 21:52 UTC, DonnieBLT requested changes
also can translate the "Ant plan" etc

2023-10-09 03:39 UTC, DonnieBLT requested changes
It's looking good just a few places where the project name is mentioned please make sure it's a variable and that it's not in a translation file

2023-10-09 03:39 UTC, DonnieBLT commented on locale/de/LC_MESSAGES/django.po
> +"OWASP BLT ist ein Fehlerprotokollierungstool, um Probleme zu melden und "
Let's have this be the project name so separate this out

2023-10-09 03:39 UTC, DonnieBLT commented on website/templates/index.html
> +                    </br> {% trans "Examples" %} {% now "F" %}. {% trans "Be first to find issues" %}!
Check this - I think it needs to say leaderboard reset for

2023-10-09 03:39 UTC, DonnieBLT commented on website/templates/index.html
> +        <h1 class="page-sub-header">Bugheist is 100% {% trans "free to use" %}, {% trans "Open Source and a non-commercial" %}, {% trans "not for profit initiative" %}.</h1>
Change bugheist to the project name, variable

2023-10-09 07:45 UTC, JisanAR03 commented
> It's looking good just a few places where the project name is mentioned please make sure it's a variable and that it's not in a translation file

after solve those i made i more commit please check it out sir

2023-10-09 13:27 UTC, DonnieBLT commented on website/templates/account/login.html
> +          OWASP BLT {% trans 'is a bug logging tool to report issues and get points, companies are held accountable' %}.
here is another spot where OWASP BLT should be replaced with the {% PROJECT_NAME %} so in general - all areas where it says "Bugheist" or "OWASP BLT" should be  {% PROJECT_NAME %}

2023-10-09 13:27 UTC, DonnieBLT commented on website/templates/account/signup.html
> +          OWASP BLT {% trans 'is a bug logging tool to report issues and get points, companies are held accountable' %}.
same here

2023-10-09 13:28 UTC, DonnieBLT commented on website/templates/index.html
> +        <h1 class="page-sub-header">{% env 'PROJECT_NAME' %} is 100% {% trans "free to use" %}, {% trans "Open Source and a non-commercial" %}, {% trans "not for profit initiative" %}.</h1>
This looks good, this is how it should be

2023-10-09 13:29 UTC, DonnieBLT commented on website/templates/account/login.html
> +          OWASP BLT {% trans 'is a bug logging tool to report issues and get points, companies are held accountable' %}.
```suggestion
          {% env 'PROJECT_NAME' %} {% trans 'is a bug logging tool to report issues and get points, companies are held accountable' %}.
```

2023-10-09 13:29 UTC, DonnieBLT commented on website/templates/account/signup.html
> +          OWASP BLT {% trans 'is a bug logging tool to report issues and get points, companies are held accountable' %}.
```suggestion
          {% env 'PROJECT_NAME' %} {% trans 'is a bug logging tool to report issues and get points, companies are held accountable' %}.
```

2023-10-09 13:33 UTC, JisanAR03 commented
@DonnieBLT I'm sorry sir ,, i should notice that one,, should i commit one more commit sir?

2023-10-09 13:44 UTC, DonnieBLT commented
I think {% load custom_tags %} has to be added to two of the templates

2023-10-09 13:47 UTC, JisanAR03 commented
> {% load custom_tags %}

"{% load custom_tags %}" is already exist sir on those two file 
ScreesShot:
![image](https://github.com/OWASP/BLT/assets/97744811/e7f6362f-e14f-487e-bf3d-6a0b46872fca)
![image](https://github.com/OWASP/BLT/assets/97744811/46afdb37-9aeb-43f3-8e08-aa631a352ac3)

2023-10-09 13:49 UTC, DonnieBLT commented
yeah not sure why it's not passing - I think it may have something to do with it being in the accounts folder

2023-10-09 13:50 UTC, JisanAR03 commented
> yeah not sure why it's not passing - I think it may have something to do with it being in the accounts folder
sir when i check this on my local site it's showing error for .env file

2023-10-09 13:53 UTC, JisanAR03 commented
> yeah not sure why it's not passing - I think it may have something to do with it being in the accounts folder

sir i check this one again and it's work fine for signup and login page sir ..can you please check this out for one more time

2023-10-09 14:02 UTC, JisanAR03 commented
> yeah not sure why it's not passing - I think it may have something to do with it being in the accounts folder

@DonnieBLT  yes sir that was my mistake i didn't add "{% load custom_tags %}" now i wish everything works fine ..sorry for not understand the issue on first try .

2023-10-09 14:25 UTC, DonnieBLT approved these changes
Nice work!  Thank you for this useful contribution.

2023-10-09 14:25 UTC, merged

2023-10-09 14:26 UTC, JisanAR03 commented
@DonnieBLT  Thank you so much for you time sir