Removed Bootstrap class and migrated Navbar to Tailwind CSS
OWASP-BLT/BLT pull request #1446
Opened 2023-09-29 17:11 UTC by thedudeontitan

Replacing Bootstrap classes with TailwindCSS Fixes: #1412

Navbar made with TailwindCSS:

![image](https://github.com/OWASP/BLT/assets/97180942/064ec4d7-67a6-41f1-b33b-215664da6d72)

![image](https://github.com/OWASP/BLT/assets/97180942/ebcfebef-359c-4780-a25b-64daa607d964)

2023-10-06 00:46 UTC, DonnieBLT requested changes
just two np

2023-10-17 20:01 UTC, DonnieBLT requested changes
needs the trans tags

2023-10-17 20:01 UTC, DonnieBLT commented on website/templates/includes/navbar.html
> +                    Report a Bug
please make sure to add the trans tags

2023-10-25 09:53 UTC, thedudeontitan commented
Added the trans tags

2023-10-28 16:24 UTC, DonnieBLT commented
I am not sure why there was added javascript, can you please take another look at this?  I think the task may have been solved with just tailwind and no needed js.  Feel free to reopen the PR with the changes.  Thank you.

2023-10-28 16:24 UTC, closed without merging