Fixed bug: Addressed issues with reply and edit comment features in the comment section.
OWASP-BLT/BLT pull request #1680
Opened 2024-01-18 18:40 UTC by kr-2003

Addressed issues with reply and edit comment features in the comment section.

### Preview

https://github.com/OWASP/BLT/assets/96587705/edda8e0b-3b02-48f7-a89c-8a3a74dc30f8

2024-01-19 13:29 UTC, kr-2003 commented
@DonnieBLT Kindly review this PR.

2024-01-20 12:57 UTC, DonnieBLT requested changes
One small tweak then looks ok

2024-01-20 13:38 UTC, kr-2003 commented on .gitignore
Sure.

2024-01-22 03:39 UTC, kr-2003 commented
@DonnieBLT Please review it. I already did the required changes.

2024-01-22 03:51 UTC, DonnieBLT approved these changes

2024-01-22 03:53 UTC, merged