Newhome layout (made it responsive)
OWASP-BLT/BLT pull request #1682
Opened 2024-01-19 15:29 UTC by Prakhar-Shankar

Issue #1617 

Now in mobile view we are following this sequence - 
1) Navbar
2) Report Section 
3) Reported Bugs
4) Leaderboard

**Mobile View**

![image](https://github.com/OWASP/BLT/assets/97254881/02dc039b-07c6-40e7-a7e7-5ae7d6244d23)

![image](https://github.com/OWASP/BLT/assets/97254881/b6103490-d56d-44bb-90b7-617bc86cbc77)

![image](https://github.com/OWASP/BLT/assets/97254881/9f4a7e6e-9b39-4f83-925b-9f9747834124)

**Desktop view**

![image](https://github.com/OWASP/BLT/assets/97254881/7c9e118e-ac9b-4101-a26f-ffa0f5c5eecd)

2024-01-29 09:37 UTC, DonnieBLT requested changes
A couple tweaks

2024-01-29 09:37 UTC, DonnieBLT commented on website/templates/new_home.html
> +    <div class="col-md-12 ">
Why a space here?

2024-01-29 09:37 UTC, DonnieBLT commented on website/templates/new_home.html
> +        <!-- <section class="hero-bugs-container grid grid-rows-2 gap-[25px] mx-[4%] my-[2.5rem] sm:max-w-screen-3xsm">
Can remove this?

2024-01-30 14:21 UTC, Prakhar-Shankar commented on website/templates/new_home.html
> +        <!-- <section class="hero-bugs-container grid grid-rows-2 gap-[25px] mx-[4%] my-[2.5rem] sm:max-w-screen-3xsm">
sure doing it right now.

2024-01-30 14:57 UTC, Prakhar-Shankar commented
> A couple tweaks

@DonnieBLT  I have made the changes sir.

2024-02-04 07:02 UTC, DonnieBLT approved these changes

2024-02-08 04:35 UTC, DonnieBLT approved these changes

2024-02-08 04:37 UTC, merged