Task done: Embedded screenshots in markdown description(API for save images).
OWASP-BLT/BLT pull request #1725
Opened 2024-01-29 19:35 UTC by kr-2003

Fixed #1206 

Added the functionality of embedding screenshots in markdown description in the form of ```$[img1]```,  ```$[img2]```, ```$[img3]```, ```$[img4]```, and ```$[img5]```.

Also added description section in issue page.(Wasn't added in the first place).

https://github.com/OWASP/BLT/assets/96587705/7e75e766-8c2c-4dd1-a7c9-6a604c6ad3ad

2024-01-29 19:39 UTC, kr-2003 commented
@DonnieBLT Kindly review this PR.

2024-01-31 02:09 UTC, DonnieBLT commented on website/templates/issue.html
> +<script src="https://cdnjs.cloudflare.com/ajax/libs/showdown/1.9.1/showdown.min.js"></script>
> ## Inclusion of functionality from an untrusted source
> 
> Script loaded from content delivery network with no integrity check.
> 
> [Show more details](https://github.com/OWASP/BLT/security/code-scanning/98)

2024-01-31 02:09 UTC, DonnieBLT requested changes
Please see the security alert. Also, could you possibly include a video showing it working?

2024-01-31 02:27 UTC, kr-2003 commented on website/templates/issue.html
> +<script src="https://cdnjs.cloudflare.com/ajax/libs/showdown/1.9.1/showdown.min.js"></script>
Added integrity check.

2024-01-31 02:29 UTC, kr-2003 commented
@DonnieBLT  I added the integrity check when including a cdn. Is there any other changes need to be done?

2024-02-04 03:56 UTC, DonnieBLT approved these changes

2024-02-04 03:57 UTC, DonnieBLT commented
Nice work, thank you!

2024-02-04 03:58 UTC, merged