On hidden issues, Request access feature
OWASP-BLT/BLT pull request #1729
Opened 2024-01-30 16:01 UTC by HanilJain

- on accessing hidden issues it will direct them to page(issue/<int:pk>/request_access/)
  with mentioning < issue has been hidden by the user that reported it.>

- on requesting access it will email to the user for the access

2024-01-30 16:08 UTC, HanilJain commented
## Additional Feature to be added 

which will be fixed in this issue #1685 

#### Feature description 

- individual user can see their hidden issues in dedicated page to it 
- user could edit access to issues and user you can view it

2024-02-08 04:44 UTC, DonnieBLT requested changes
This looks similar to the other whole request. Can you please close the one that is not required and only keep the one that has all the changes required open?

2024-02-08 04:44 UTC, DonnieBLT commented on blt/urls.py
> +    path("issue/<int:slug>/" , IssueView.as_view() , name = "issue_view"),
Can keep this how it is

2024-02-08 20:31 UTC, HanilJain commented
closing this pull request as all additional feature including this have been added in #1737

2024-02-08 20:31 UTC, closed without merging