Rate Limiting added to 'IssueBaseCreate' and 'IssueCreate'
OWASP-BLT/BLT pull request #1747
Opened 2024-02-05 09:47 UTC by ATHARVA-GAWAS

2024-02-08 06:27 UTC, DonnieBLT requested changes
Tweaks

2024-02-08 06:27 UTC, DonnieBLT commented on website/views.py
> +from django.http import HttpResponse
These seem like they can be removed

2024-02-08 14:55 UTC, ATHARVA-GAWAS commented
I have made the suggested changes

2024-02-09 02:02 UTC, DonnieBLT requested changes
Please remove the remaining unused imports

2024-02-09 13:56 UTC, ATHARVA-GAWAS commented
I have made the changes

2024-02-13 10:53 UTC, DonnieBLT requested changes
Why is this removing the stype code?

2024-02-15 14:14 UTC, DonnieBLT requested changes
We want this to be site wide. Can you please add it to the middleware? Also please remove any white space changes (changes to lines with no code)

2024-02-17 06:29 UTC, closed without merging