Step 1: Create the Django model Define a Django model named 'Monitor' with fields such as 'url', 'keyword', 'last_checked_time', 'status', and 'user'. #1897
OWASP-BLT/BLT pull request #1981
Opened 2024-03-09 04:14 UTC by Sarthak5598

#1897

2024-03-09 05:42 UTC, DonnieBLT requested changes
Can you also add the created and modified fields as well as the migration and the class for the admin?

2024-03-09 19:01 UTC, DonnieBLT requested changes
Please also add the form to create an entry as well as the created / modified field names.

2024-03-13 13:58 UTC, Sarthak5598 commented
sorry, I forgot about this, I will make the changes !!

2024-03-13 18:23 UTC, Sarthak5598 commented
![image](https://github.com/OWASP-BLT/BLT/assets/108613416/7aaaa787-9e5d-48a3-b708-49605d83276b)

2024-03-15 20:36 UTC, DonnieBLT requested changes
Almost there we also need a created and modified field. Please see the other table for an example.

2024-03-21 15:12 UTC, arkid15r commented on website/views.py
> +    return render(request, "Moniter.html", {"form": form})
```suggestion
    return render(request, "monitor.html", {"form": form})
```

2024-03-21 15:12 UTC, arkid15r commented on website/views.py
> +    return render(request, "Moniter.html", {"form": form})
Do you use this view anywhere?

2024-03-21 15:12 UTC, arkid15r commented on website/views.py
> +    return render(request, "Monitor.html", {"form": form})
Based on the  current `templates` directory naming convention:
```suggestion
    return render(request, "monitor.html", {"form": form})
```

2024-03-21 17:56 UTC, Sarthak5598 commented on website/views.py
> +    return render(request, "Moniter.html", {"form": form})
Ohh! forgot about that thanks

2024-03-23 16:58 UTC, DonnieBLT approved these changes

2024-03-23 16:58 UTC, merged