redesigning issue description page - 2
OWASP-BLT/BLT pull request #1982
Opened 2024-03-09 11:20 UTC by CodeWithBishal

created a layout for the page
created a sidebar for like,dislike,flag, and other btns
page is reponsive
files formatted using pre-commit run --all-files
todo add bookmark

Before
<img width="1440" alt="Screenshot 2024-03-09 at 4 49 58 PM" src="https://github.com/OWASP-BLT/BLT/assets/69814108/7cc48cab-fc1e-4323-9648-739d798c26ef">

After
<img width="1440" alt="Screenshot 2024-03-09 at 4 49 33 PM" src="https://github.com/OWASP-BLT/BLT/assets/69814108/ffc3ba13-fc5c-473d-9cb6-eb6584cf07dc">
<img width="389" alt="Screenshot 2024-03-09 at 4 49 43 PM" src="https://github.com/OWASP-BLT/BLT/assets/69814108/5b97431b-1d84-4f51-ad75-3ef1e68a9fc1">

2024-03-09 13:05 UTC, CodeWithBishal commented on website/templates/issue3.html
> +            <a href="{{ object.url }}" class="text-red-600" target="_blank">{{ object.url | truncatechars:100 }}</a>
Fixed now :)

2024-03-09 16:31 UTC, CodeWithBishal commented
@DonnieBLT  Okay I can get back /issue/ page working but changing the design here would mean I have to again start from scratch.

2024-03-10 10:58 UTC, CodeWithBishal commented
@DonnieBLT yes the end goal is to replicate the same UI, I am just creating the layout now and incorporating some basic features

2024-03-10 13:19 UTC, DonnieBLT requested changes
We can merge this when the previous issue URLs are working

2024-03-12 16:31 UTC, DonnieBLT approved these changes

2024-03-12 16:36 UTC, CodeWithBishal commented
@DonnieBLT Sure,

Should I update the branch? there is only one merge conflict with base.html

2024-03-12 16:43 UTC, merged