Created API's for Get Open and Closed Issues
OWASP-BLT/BLT pull request #2090
Opened 2024-05-11 17:36 UTC by Uttkarsh-raj

This pr is regarding getting the open and closed issues for a domain. The domain must be sent as a query in the API call.
## Request:
```
http://localhost:8000/open-issues/?domain=http://www.blt.com
``` 
## Response:
```
{
  "count": 1,
  "result": [
    {
      "id": 3,
      "user": {
        "id": 1,
        "username": "admin"
      },
      "url": "https://youtu.be/kopl",
      "description": "sdfasfdsaf",
      "markdown_description": "sdfasdfsfsdfsa",
      "label": 0,
      "views": 1,
      "verified": false,
      "score": null,
      "status": "open",
      "user_agent": null,
      "ocr": "",
      "screenshot": "/media/screenshots/Screenshot_44.png",
      "closed_date": null,
      "github_url": null,
      "created": "2024-05-10T19:12:27.348276Z",
      "modified": "2024-05-11T13:04:08.699875Z",
      "is_hidden": false,
      "rewarded": 0,
      "reporter_ip_address": null,
      "cve_id": null,
      "cve_score": null,
      "hunt": null,
      "domain": 2,
      "closed_by": null,
      "team_members": [
        1
      ]
    },
  ]
}
```
![Screenshot (104)](https://github.com/OWASP-BLT/BLT/assets/106571927/11c59576-e2ee-4e1d-80d8-cbf3a6bf116c)
![Screenshot (105)](https://github.com/OWASP-BLT/BLT/assets/106571927/9a725516-a0ad-4ed5-86aa-2fc7099a8c80)

Similar for the Closed API.

![Screenshot (106)](https://github.com/OWASP-BLT/BLT/assets/106571927/eda9f949-4226-404c-adc6-fc10f633d4c6)

2024-05-11 17:54 UTC, arkid15r reviewed
Nicely done, please find my comments below:

2024-05-11 17:54 UTC, arkid15r commented on website/api/views.py
Great work figuring out the `viewsets`! 

It looks like your Open/Closed issue views separation approach isn't going along with DRY (do not repeat yourself)  principle. I suggest using a single viewset and branch logic purely based on the URL parameter specifying issue's status (open/closed). Something like

`path("issues/<str:status>", IssuesViewSet.as_view({"get": "get"}), name="issues")`

Here you need to make sure the URL doesn't clash with existing mapping and it'd also be great to narrow down the status options to ["open", "closed"].

2024-05-11 17:54 UTC, arkid15r commented on website/api/views.py
> +            domainData = Domain.objects.get(url=domainUrl)
Snake case please

2024-05-11 17:54 UTC, arkid15r commented on website/api/views.py
> +        except ObjectDoesNotExist:
You could narrow it down to `Issue.DoesNotExist` exception

2024-05-12 07:29 UTC, Uttkarsh-raj commented
> You can accomplish this by adding a filter to the existing endpoint

something like this issues/?status="open"&domain="www.blt.com" ?

2024-05-13 12:18 UTC, Uttkarsh-raj commented
Please review this approach i tried. The output is the required one but i want to know if this approach is correct or not.
![Screenshot (107)](https://github.com/OWASP-BLT/BLT/assets/106571927/bbd4d9df-0275-4ff6-8290-c9d96e6245ed)
![Screenshot (108)](https://github.com/OWASP-BLT/BLT/assets/106571927/d0923f80-cc34-4c23-8de9-659129a9930d)
![Screenshot (109)](https://github.com/OWASP-BLT/BLT/assets/106571927/ac218f57-8725-49e7-9694-9fc2a8440ab1)
![Screenshot (110)](https://github.com/OWASP-BLT/BLT/assets/106571927/d65c64d1-02c9-4166-b064-fa18f75c7805)

2024-05-13 15:36 UTC, Uttkarsh-raj commented
> This looks right

Plz review the code too...Thanks..

2024-05-13 16:04 UTC, Uttkarsh-raj commented
> You can update the existing code here https://github.com/OWASP-BLT/BLT/blob/main/website/api/views.py

Can you specify the changes needed.

2024-05-13 17:40 UTC, arkid15r commented
> Can you specify the changes needed.

Try playing with  https://www.django-rest-framework.org/api-guide/filtering/

2024-05-14 19:17 UTC, Uttkarsh-raj commented
> Try playing with https://www.django-rest-framework.org/api-guide/filtering/
Please review these changes. Thank you.

2024-05-14 19:33 UTC, DonnieBLT requested changes

2024-05-14 19:56 UTC, Uttkarsh-raj commented
@DonnieBLT made these changes. Thanks for this. Any other changes needed?

2024-05-15 16:47 UTC, arkid15r reviewed
It looks much better now, @Uttkarsh-raj!

Thanks for addressing all comments!

LGTM

2024-05-15 16:54 UTC, DonnieBLT approved these changes

2024-05-15 17:31 UTC, merged

2024-05-15 17:32 UTC, Uttkarsh-raj commented
> It looks much better now, @Uttkarsh-raj!
> Thanks for addressing all comments!
> LGTM

Thanks for all the reviews have really learnt a lot from this...