added langchain adn openai to poetry
OWASP-BLT/BLT pull request #2366
Opened 2024-06-20 15:52 UTC by Sarthak5598

2024-06-20 15:53 UTC, Sarthak5598 reviewed
Not ready for merge now , Just want to keep it open as everyone is working on it , Would like to know everyones opinion

2024-06-21 19:06 UTC, Sarthak5598 commented
Hey, can anyone help me with this? For some reason, the `AutoLabel` function isn't getting the `bugdescription`. I've console logged everything, and it's correct from the `report.html` side. It's even getting the label from the function (JSON response), but it can't get `bugdescription` from `report.html`.

2024-06-21 19:17 UTC, Sarthak5598 commented
Works now !!, no need for a review as of now, thanks

2024-06-21 20:05 UTC, Sarthak5598 commented
The new implementation works as intended for setting the label but the issue is that the bug reports are no longer being posted on the main page as they used to be. It seems that the issue may be related to how the bug reports are handled after the label selection is done. please help

2024-06-28 17:55 UTC, arkid15r requested changes

2024-06-28 17:55 UTC, arkid15r commented on blt/urls.py
> +    path("AutoLabel/", AutoLabel, name="AutoLabel"),
Could you use something like
```suggestion
    path("issue-auto-label/", AutoLabel, name="AutoLabel"),
```

2024-06-28 17:55 UTC, arkid15r commented on website/templates/report.html
> +                    <button id="GenerateLabel"
It looks like id should start from lowercase character.

2024-06-28 17:55 UTC, arkid15r commented on website/views.py
> +    dotenv_path = Path("blt\.env")
```suggestion
    dotenv_path = Path("blt/.env")
```

2024-06-28 17:55 UTC, arkid15r commented on website/views.py
> +    Token_per_prompt = 70
```suggestion
    token_limit = 1000
    token_per_prompt = 70
```

2024-06-28 17:55 UTC, arkid15r commented on website/views.py
> +        print(bug_description)
Please remove

2024-06-29 19:06 UTC, arkid15r reviewed
LGTM

2024-06-29 19:06 UTC, arkid15r commented on blt/urls.py
> +    path("issue-auto-label/", AutoLabel, name="AutoLabel"),
Please follow the existing naming templates for function based views next time.

2024-06-29 19:17 UTC, arkid15r approved these changes

2024-06-29 19:17 UTC, merged