Bitcoin address validation using JavaScript
OWASP-BLT/BLT pull request #2400
Opened 2024-07-04 18:46 UTC by CodeWithBishal

added a javascript file containing 3 functions. Each of the function represent each of the crypto address.

### TO Use
include the javascript file, call the respective function with the address and the function will return true if it is a valid crypto address

### TO Test
I have included a list of some demo crypto address to test each of the validator, TO Test: uncomment  the respective validator and open the browser console on the page where the js file is included.

I will integrate this code with the profile page once, the profile page is completed

Thanks

this closes #2282

2024-07-04 18:56 UTC, DonnieBLT requested changes
This looks good, can you please also integrate it into the site where the user enters addresses - on the profile page and on the bid page

2024-07-04 18:58 UTC, CodeWithBishal commented
Sure!

2024-07-04 19:45 UTC, CodeWithBishal commented
@DonnieBLT hey, so I found that user's crypto address is being updated only on the profile page, so I added the validator here,

I have checked bidding.html and bid_selection.html but couldn't find any forms updating the user's crypto address

this closes #2282

2024-07-06 18:02 UTC, DonnieBLT approved these changes

2024-07-06 18:08 UTC, merged