integrate bugs List in company dashboard
OWASP-BLT/BLT pull request #2442
Opened 2024-07-12 21:58 UTC by JisanAR03

@DonnieBLT , this is another PR for complete the company dashboard part. now from company dashboard user can see those bugs which is reported for there available domain

2024-07-15 21:39 UTC, DonnieBLT requested changes

2024-07-16 10:32 UTC, JisanAR03 commented
> @JisanAR03 can you please show a screenshot?

@DonnieBLT , here is the screenshot. and now I make one more commit for add the github and figma link again

![image](https://github.com/user-attachments/assets/fd563b3e-bd9c-45a3-abbc-5ed0093cea16)

2024-07-16 10:53 UTC, JisanAR03 commented on company/templates/company/company_manage_bugs.html
added

2024-07-16 15:49 UTC, DonnieBLT approved these changes

2024-07-16 15:49 UTC, merged