add ability to block ip addresses that are submitting spam #1938
OWASP-BLT/BLT pull request #2622
Opened 2024-08-09 20:08 UTC by Sarthak5598

#1938

2024-08-09 20:19 UTC, DonnieBLT requested changes
looking good, a few more tweaks please

2024-08-11 06:23 UTC, Sarthak5598 commented on website/models.py
> +    count = models.IntegerField(default=1)
its for the number of requests a user made

2024-08-11 06:39 UTC, Sarthak5598 commented on blt/middleware/ip_restrict.py
> +    def ip_in_range(self, ip, ip_ranges):
okay!

2024-08-12 18:34 UTC, DonnieBLT requested changes
Can you please update the migration? I think it's using the old name.

2024-08-13 13:59 UTC, DonnieBLT requested changes
One change

2024-08-13 16:39 UTC, DonnieBLT approved these changes

2024-08-13 16:40 UTC, merged