add management-command
OWASP-BLT/BLT pull request #2775
Opened 2024-10-13 21:43 UTC by sagnik3788

Fix  #1898 
![Screenshot 2024-10-14 010832](https://github.com/user-attachments/assets/7c6e1b02-61c7-4141-b4c1-b66115aed8e5)

2024-10-16 00:34 UTC, DonnieBLT submitted a review, later dismissed

2024-10-17 16:59 UTC, DonnieBLT requested changes
Can you please update it so that if the status changes it sends an email to the user?

2024-10-17 17:07 UTC, sagnik3788 commented
Should I update this in this PR, or add another for #1900?

2024-10-19 20:05 UTC, DonnieBLT approved these changes

2024-10-19 20:06 UTC, merged