Report Malicious IPs
OWASP-BLT/BLT pull request #2867
Opened 2024-11-05 15:03 UTC by krrish-sehgal

**Fixes**: #2591

## Description

This PR introduces a feature that allows users to report suspicious IP addresses with a description and title, targeting IPs involved in unauthorized activities such as phishing, scanning, and attacks.

### Changes Implemented

- **Model**: 
  - `ReportIP` model with migration to store user-reported IP addresses and other details.
- **Forms**: 
  - `IpReportForm` to facilitate user submissions of IP reports.
- **Views**: 
  - **`ReportIpView`**: Handles GET and POST requests to display and process the report IP form.
  - **`MaliciousIpListView`**: Displays a list of all IP addresses reported by users for easy tracking and review.
- **Navigation**:
  - Added options in the side and top navbars to access this feature.
- **python version made generic**

### New Templates Created

- `report_ip.html`: Renders the form for users to report IPs.
- `malicious_ips_list.html`: Lists all IPs reported for malicious activities.

### More features that can be added in further updates: 
- `Like and Dislike Feature: Implementing a feedback mechanism to allow users to express their opinions on reported IPs.`
-`Duplicate Check: Adding this button in from to allow users to browse through the IPs.`
-`IP Search Functionality: Developing a search feature to allow users to easily find specific reported IPs.`

### Attached Demo
[Video demo of the feature](https://github.com/user-attachments/assets/db12fb47-da9b-4e78-8ae7-1bef7b05fe76)

2024-11-06 15:43 UTC, DonnieBLT requested changes
Looks good thank you can you please make a few tweaks?

2024-11-07 10:17 UTC, krrish-sehgal commented
I have made the model and names in the form more generic and have addressed all the changes that were requested including allowing users to select the type of activity ie (friendly or malicious).

I have also included a ip validation from the backend as well now.

The new reported_ips_list page looks something like this : 
<img width="1470" alt="Screenshot 2024-11-07 at 3 46 52 PM" src="https://github.com/user-attachments/assets/d8ff2b0c-b9c9-423f-b3d6-2acb6443a24f">

2024-11-07 13:52 UTC, DonnieBLT approved these changes

2024-11-07 13:58 UTC, DonnieBLT requested changes
Can you please check the code scanning alerts?

2024-11-07 14:12 UTC, krrish-sehgal commented
> Can you please check the code scanning alerts?

Sure, on it.

2024-11-07 19:39 UTC, DonnieBLT submitted a review, later dismissed

2024-11-10 04:23 UTC, krrish-sehgal commented
the conflicts have been resolved in my last commit , thanks.

2024-11-10 05:58 UTC, DonnieBLT submitted a review, later dismissed

2024-11-10 21:06 UTC, DonnieBLT requested changes
We are no longer using the contributor stats table

2024-11-11 14:49 UTC, DonnieBLT submitted a review, later dismissed

2024-11-11 14:53 UTC, krrish-sehgal commented
@DonnieBLT , any feedback as to why this test case always fails?

2024-11-11 15:15 UTC, krrish-sehgal commented
Could you kindly merge the current changes before proceeding with any further merges? This will help in avoiding any potential conflicts.

2024-11-11 15:22 UTC, DonnieBLT requested changes

2024-11-11 17:16 UTC, krrish-sehgal commented on website/templates/includes/header.html
sure sir , on it.

2024-11-12 02:10 UTC, DonnieBLT requested changes

2024-11-13 04:54 UTC, DonnieBLT requested changes
One tweak

2024-11-13 04:57 UTC, krrish-sehgal commented
> One tweak

Sir , you mentioned that the report-ip button would be good on a page , not the side-nav , could you specify which page you are referring ?  Is it the home page like i mentioned before ?

2024-11-13 05:04 UTC, krrish-sehgal commented
sure , got it.

2024-11-13 12:23 UTC, krrish-sehgal commented
@
<img width="1469" alt="Screenshot 2024-11-13 at 5 53 12 PM" src="https://github.com/user-attachments/assets/07c95a08-26a9-4a17-9fbf-5b8dbe7d90c6">

this button will appear on this page only and looks clean.

2024-11-13 14:10 UTC, DonnieBLT approved these changes

2024-11-13 14:11 UTC, merged