Responsive design for projects page
OWASP-BLT/BLT pull request #2870
Opened 2024-11-06 03:29 UTC by dhruvkrishnavaid

2024-11-07 13:33 UTC, DonnieBLT approved these changes

2024-11-07 14:07 UTC, DonnieBLT submitted a review, later dismissed

2024-11-10 00:44 UTC, DonnieBLT requested changes
one tweak please

2024-11-24 01:46 UTC, DonnieBLT requested changes
There are some conflicts here can you please resolve them?

2024-11-28 13:28 UTC, dhruvkrishnavaid commented
# Before
<img width="1710" alt="Screenshot 2024-11-28 at 6 30 15 PM" src="https://github.com/user-attachments/assets/641cfe87-eec4-423b-bb18-bcc5f558ff07">
<img width="1710" alt="Screenshot 2024-11-28 at 6 30 37 PM" src="https://github.com/user-attachments/assets/d6c1c712-de00-4839-a094-34b1b1e4ab81">
<img width="1710" alt="Screenshot 2024-11-28 at 6 32 32 PM" src="https://github.com/user-attachments/assets/ffa0443e-dbfc-4e24-9f83-dc56ac4071b4">

# After
<img width="1710" alt="Screenshot 2024-11-28 at 6 54 51 PM" src="https://github.com/user-attachments/assets/1eb299c4-6a91-42bc-bf44-86c84728adfe">
<img width="1710" alt="Screenshot 2024-11-28 at 6 54 44 PM" src="https://github.com/user-attachments/assets/d70c7c5a-bbc0-4feb-95fb-0b221204344b">
<img width="1710" alt="Screenshot 2024-11-28 at 6 56 00 PM" src="https://github.com/user-attachments/assets/a497041e-b701-4434-9dec-2915ef30d33f">

2024-12-13 01:14 UTC, DonnieBLT approved these changes

2024-12-13 01:14 UTC, merged