Added logic to fetch README files, documentation, commit messages, an…
OWASP-BLT/BLT pull request #2919
Opened 2024-11-13 09:59 UTC by SahilDhillon21

…d issue trackers from repository APIs.

**Related issue**: https://github.com/OWASP-BLT/BLT/issues/2681

- Updated Project model to include fields for README content, documentation links, commit summaries, and issue tracker counts.
- Implemented API calls in update_projects.py to gather and save this data to the database.

![readme ss](https://github.com/user-attachments/assets/c13ff975-d613-4a2f-91b3-9c8d5343dd72)

Fixed the migration file issue that I was facing in the previous PR.

I had to remove the line "Authorization": f"token {settings.GITHUB_TOKEN}" from the header as it was giving an error saying 'Unable to fetch repository - 401'. I was unsure how to deal with it so I have removed it for now.

2024-11-13 11:47 UTC, SahilDhillon21 commented
@DonnieBLT I believe for the CodeQL test the languages should be python, javascript; instead of being 'python javascript'. Though  I am unsure about how to fix this.

2024-11-13 18:50 UTC, SahilDhillon21 commented
I've added the GitHub token and fixed the formatting. Please review and let me know.

2024-11-19 02:29 UTC, DonnieBLT requested changes
Can you please check the comments?

2024-11-19 08:57 UTC, SahilDhillon21 commented on website/management/commands/update_projects.py
> +                project.issue_tracker_url = f"https://github.com/{repo_name}/issues"
Understood.

2024-11-19 15:08 UTC, SahilDhillon21 commented
I have integrated a basic summary model "facebook/bart-large-cnn". However, due to the large variations in the readme files of the repositories, the summaries aren't too effective. I had thought of pre-processing the content to only pass relevant sections, but even that seems to be difficult since there is no particular structure followed. @DonnieBLT which direction should I look into to improve this? Though openai API is paid, it could do the job really well compared to the generic python models

2024-11-20 21:42 UTC, SahilDhillon21 commented
Hello @DonnieBLT, here's an overview of the search functionality: 
[projects-search-function.webm](https://github.com/user-attachments/assets/0540e719-9dc7-401b-b961-9ce760232fde)
It filters based on the project name, a summary, and ai labels.

Looking forward to your feedback.

2024-11-24 01:43 UTC, DonnieBLT requested changes
requesting a few changes, we're almost there

2024-11-24 12:42 UTC, SahilDhillon21 commented on website/management/commands/update_projects.py
> +                        project.ai_labels = json.loads(generate_labels(readme_text, project.topics))
I found the AI-generated labels to be more accurate and effective, but we can surely use these topics directly. I'll modify it

2024-11-24 12:55 UTC, SahilDhillon21 commented on website/templates/website/project_list.html
> +            <form id="search-form" class="search-form">
The search bar in the header functions slightly differently. Upon entering a query and selecting a label, it transitions to another search bar specific to the selected label. This second search bar is more focused and offers only four distinct labels to refine the search (issue, domain, user, label). It doesn't allow you to search for say specific projects or orgs.

This search form filters exclusively on project's description, labels and name. Let me know if you want to remove this and and fix the header search form to include projects and organizations

2024-11-24 13:25 UTC, SahilDhillon21 commented on website/templates/website/project_list.html
> -        <ul class="project-list">
So I assume we don't want to create a separate template and have all the code here itself? Let us finalize what to do with the search function and I'll make the changes accordingly

2024-11-24 14:01 UTC, SahilDhillon21 commented on website/management/commands/update_projects.py
> +                        project.ai_labels = json.loads(generate_labels(readme_text, project.topics))
Done

2024-11-24 14:09 UTC, SahilDhillon21 commented
Have made most of the changes, just need a final heads-up on what to do with the search functionality as it's quite buggy and limited. Should I create a new PR to improve its working if we go that route?

2024-11-28 05:01 UTC, DonnieBLT requested changes
A few adjustments request

2024-12-18 10:43 UTC, DonnieBLT submitted a review, later dismissed

2025-02-14 19:27 UTC, closed without merging