fix: fix the position of logout modal on page
OWASP-BLT/BLT pull request #2943
Opened 2024-11-17 12:16 UTC by 1010varun

fixes: #2938 

I added the flex to make the modal center of the page.

2024-11-18 14:44 UTC, 1010varun commented
But @DonnieBLT, don't you think doing this will affect the current alignment of other pages. I think these are correctly aligned currently.

2024-11-19 02:17 UTC, DonnieBLT requested changes
Please have this change be at the base level, so it applies to all the pages in allauth

2024-11-19 07:40 UTC, 1010varun commented
Surely le me do that

2024-11-21 16:19 UTC, DonnieBLT requested changes
This should work with only one file the base file

2024-11-22 12:24 UTC, 1010varun commented
@DonnieBLT there is a change only in base.html, in logout.html I have made a whole new modal for logout that's why there are changes in that file.

previous logout:
![image](https://github.com/user-attachments/assets/1c064cc0-4cc5-4f63-96d0-b07b6887dcbd)


changes in logout:
1. made a box and shadow
2. changed button color to match the theme
3. Make text to be in center of modal

![Screenshot from 2024-11-20 00-13-49](https://github.com/user-attachments/assets/82473ccf-31ce-46e2-a7db-60023f5141d9)

2024-11-24 00:30 UTC, DonnieBLT requested changes
please make it the base.html only - the base.html should go in the allauth or account folder so it overrides the allauth one

2024-11-24 12:16 UTC, harsh3dev commented
@1010varun still working on this one?

2024-11-24 13:11 UTC, 1010varun commented
Yess

2024-11-24 13:42 UTC, 1010varun commented
@DonnieBLT, I think there is some misunderstanding in this PR there are changes in two file:
1. base.html 
2. Logout.html

the changes in base.html make all the auth pages in the enter of screen and changes in logout.html are done so to create a new modal for logout. Which is another issue(#2965). If you want I can
 make changes in base,HTML and then raise another PR for logout modal changes.

I am attaching some ss for new auth screens
![Screenshot from 2024-11-20 00-11-04](https://github.com/user-attachments/assets/8193d31f-1a4c-483a-b5e4-d6cf49af311f)
![Screenshot from 2024-11-20 00-13-49](https://github.com/user-attachments/assets/105a3644-6f5f-4c43-b83f-fa1f45f948ac)
![Screenshot from 2024-11-20 00-10-56](https://github.com/user-attachments/assets/95c53a75-f4db-43e9-b37f-5c5a1cc4fe90)

2024-11-27 14:27 UTC, 1010varun commented
@DonnieBLT can you kindly look into this PR

2024-12-13 23:46 UTC, DonnieBLT approved these changes

2025-02-20 21:39 UTC, closed without merging