Added Feature to recommend Users from profile page
OWASP-BLT/BLT pull request #2948
Opened 2024-11-18 16:37 UTC by tsu-ki

Users can recommend other uses directly from their profile page. I've also added a badge which shows the recommended users. 
Closes: https://github.com/OWASP-BLT/BLT/issues/2632

https://github.com/user-attachments/assets/5e9d1beb-b3e5-43ab-9b72-c31f9b2aeb21

2024-11-19 02:15 UTC, DonnieBLT requested changes
Please see the comment for the changes requested and also please make sure the tests are passing

2024-11-19 02:51 UTC, tsu-ki commented
@DonnieBLT can you please elaborate on what did you mean by adding number count?

2024-11-23 11:28 UTC, tsu-ki commented
Added a recommendation blurb which can be added to a User's Profile from Edit Profile Page.
Also Added a feature using which other users can recommend a user directly by clicking on a "Recommend" button which is visible to other users only(not self), without having to manually recommend a user. 
Also added a feature to show the total number of recommendations received. Retained the function to show total number of recommended users.
https://github.com/OWASP-BLT/BLT/issues/2632

https://github.com/user-attachments/assets/13f258d7-982f-4ed4-b9d8-aa03b100a3c8

2024-11-24 00:33 UTC, DonnieBLT requested changes
please see comments

2024-11-24 00:46 UTC, tsu-ki commented on .pre-commit-config.yaml
> +        language_version: python3.11
sure, i'll remove them

2024-11-24 00:49 UTC, tsu-ki commented on blt/urls.py
> +    path("recommend/<int:user_id>/", recommend_user, name="recommend_user"),
each of the 3 urls determine, recommend users manually(using the dedicated recommendation feature on user profile) , recommend directly from the button under the recommendation blurb and another is ajax recommendation(this was optional and can be removed)

2024-11-24 00:59 UTC, DonnieBLT requested changes
there are a few changes to make also did you ever get permission from @npxpatel to use his code?

2024-11-24 01:09 UTC, tsu-ki commented on website/admin.py
umm, can you please tell me which imports are missing from this file? I apologise if I missed any

2024-11-24 01:28 UTC, tsu-ki commented
> You also copied our badge to a new project without retaining the license? ![image](https://private-user-images.githubusercontent.com/128622481/389239963-5e6aab8a-401b-4ff4-b620-5b95b10a731a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI0MTE2MTIsIm5iZiI6MTczMjQxMTMxMiwicGF0aCI6Ii8xMjg2MjI0ODEvMzg5MjM5OTYzLTVlNmFhYjhhLTQwMWItNGZmNC1iNjIwLTViOTViMTBhNzMxYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyNFQwMTIxNTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMzQyYjc1NDJjYmM5ZGUyOTI1YTliM2JkMGM5ODA3NmM1MTE1M2Q3Nzc0MzUwMGI0MmQzM2EzNmJlNjVkYjdkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.aGM_hroyJaG-1XaTjMoB5Yy0OhGlguCbtdseIqmqjqE)

Actually, I created this project solely to develop a badge for BLT repository which can be used in the README.md file(https://github.com/OWASP-BLT/BLT/pull/2940) and never intended on using it anywhere else. I was going to archive the repository and delete the badge as soon as the corresponding PR for the issue was merged, I waited so just in case the badge I created could come in-use.
I apologise if this created a misunderstanding, I'll delete the created the badge so as not to cause any more confusion.
If there's anything else I can do, please do let me know, again, I'm sorry.

2024-12-03 17:01 UTC, tsu-ki commented
@DonnieBLT please review the changes I've made to execute the recommendation system and recommendation blurb.
Also, can you please explain how can I resolve the occuring conflicts?

https://github.com/user-attachments/assets/ee621fc5-6f66-477a-af2f-cc316ff3bcfd

2024-12-06 19:58 UTC, tsu-ki commented
@DonnieBLT Sir, can you please review the changes I've made and suggest any probable changes, thank you!

2024-12-14 09:30 UTC, tsu-ki commented
> this should be liked LinkedIn where you can recommend a user like "this person is a good developer, I recommend them" and it shows the date and image and name of user who recommended them.

The current implementation displays the avatar and the name of the person who has recommended the author, as a list in `Recommendations`.
The recommendations made by the the author are shown in `Recommends` following the same layout. 
I believe only the date function needs to be implemented now, if there's any other changes that I should implement, then please do let me know, thank you

2024-12-20 14:24 UTC, tsu-ki commented
@DonnieBLT sir, can you please review the changes I've made in the latest commit.
I've added:
- A date-stamp which gets added in both the cases, when a user gives a recommendation or receives one.
- The name, avatar and the profile url are displayed in both the "Recommended Users" and "Recommendation Received" lists
- Renamed 'Recommendation' to 'About Me', as it's more suitable considering the biography-nature of the Recommendation Blurb.
- A dedicated Recommend Section is displayed at the bottom of user profile, using which the users can manually search a user and recommend them, this section is only visible to the author.

https://github.com/user-attachments/assets/e255e75a-8abf-4643-b637-abdbd053cc24

2024-12-20 14:27 UTC, DonnieBLT requested changes
Can you please clean this up and remove the unnecessary files and changes check the conflict

2024-12-20 14:28 UTC, tsu-ki commented
> When you recommend a user, you should be able to insert text
Understood, should I display the text in the same Recommendations list, where the user details are displayed or create a seperate feature altogether?

2024-12-26 12:38 UTC, tsu-ki commented
@DonnieBLT Sir I've made the required corrections and resolved the conflicts, but as I had to add `# noqa: F401` tag from preventing ruff format in removing the unused imports, it's giving a conflict again. 
Can you please the conflict and resolve it?

2024-12-28 14:07 UTC, tsu-ki commented
@DonnieBLT sir can you please review the conflicts and resolve them?

2025-02-17 22:33 UTC, DonnieBLT requested changes
please make it so that recommendations are shown without having to click

2025-02-28 14:36 UTC, tsu-ki commented
@DonnieBLT sir, I've created a new PR for this. Please address to that, thank you!

2025-03-04 22:06 UTC, closed without merging