Truncation added for String length
OWASP-BLT/BLT pull request #3022
Opened 2024-11-30 02:29 UTC by tsu-ki

Fixed the string value too long error persisting in `middleware/ip_restrict.py`
Resolves this issue: https://github.com/OWASP-BLT/BLT/issues/3018

2024-12-01 16:17 UTC, DonnieBLT requested changes
I would rather increase the minimum to be 500 characters in the model thank you

2024-12-01 17:41 UTC, tsu-ki commented
> I would rather increase the minimum to be 500 characters in the model thank you

sure, I'll increase it

2024-12-02 15:34 UTC, DonnieBLT requested changes
This needs a migration file

2024-12-02 21:43 UTC, tsu-ki commented
> This needs a migration file

Can you please explain what needs to be added in the migration file? 
I initially changed the agent's field type to `TextField` in models and removed the `max_length` limit so as to increase the character limit.

2024-12-02 21:57 UTC, tsu-ki commented
> In Django, when you make a change to a model you need to run python manage.py makemigrations

..yeah, that totally skipped my mind. thank you for reminding me! I’ll run the command and push the commit

2024-12-05 03:53 UTC, DonnieBLT requested changes

2024-12-18 10:43 UTC, tsu-ki commented on website/migrations/0161_alter_badge_icon_alter_ip_agent.py
> +        migrations.AlterField(
umm, if I remove the merged migration file, wouldn't the leaf nodes become open?

2024-12-19 17:17 UTC, tsu-ki commented
@DonnieBLT sir I've removed the merge migration file but it's causing the CI/CD tests to fail. Can I please get your review on this?

2024-12-20 14:35 UTC, DonnieBLT requested changes

2025-01-01 22:51 UTC, closed without merging

2025-01-01 23:02 UTC, tsu-ki commented
> the migration did not need to apply to the badge table, so I have fixed this in another commit.

sir is it okay if I mention this PR in the leaderboard list?