fix: customize EasyMDE configuration for post form
OWASP-BLT/BLT pull request #3024
Opened 2024-11-30 10:24 UTC by harsh3dev

This PR fixes #3023 

https://github.com/user-attachments/assets/0736bbd0-3cba-4b31-a201-a6d3f9bccf1f

## Changes
* Modified the EasyMDE configuration which will hide the fullscreen toggle button as it takes the width and height of the screen
* Makes the toggle preview button to show within the text-area

2024-11-30 10:26 UTC, harsh3dev commented
@DonnieBLT Please review this one whenever you find time.
Thanks

2024-12-01 16:20 UTC, DonnieBLT approved these changes

2024-12-02 10:25 UTC, DonnieBLT submitted a review, later dismissed

2024-12-13 01:12 UTC, DonnieBLT requested changes
Can you please limit the changes to the files related to the PR / issue

2024-12-14 09:22 UTC, closed without merging