Add trademark search, update db, send email django management command
OWASP-BLT/BLT pull request #3080
Opened 2024-12-09 07:16 UTC by drvcodenta

fixes: #1025

2024-12-11 21:58 UTC, drvcodenta commented
resolved

2024-12-12 16:34 UTC, DonnieBLT requested changes
two changes please

2024-12-12 16:51 UTC, drvcodenta commented on website/models.py
> +    trademark = models.IntegerField(default=0)
ok

2024-12-12 17:39 UTC, drvcodenta commented on website/models.py
> +    trademark = models.IntegerField(default=0)
Do I need to create schedule, that checks the value every week automatically?

2024-12-15 16:27 UTC, closed without merging