Shift blog and company to website
OWASP-BLT/BLT pull request #3119
Opened 2024-12-17 13:54 UTC by krrish-sehgal

Fixes : #3118

Import to run : :python manage.py migrate --fake "
inorder to ensure that the blog_post table is not created again and the preexsisting table is used.

Video ref : 
https://github.com/user-attachments/assets/dddb5bba-a959-49de-98ed-164d9b5fd8ec

2024-12-17 14:04 UTC, krrish-sehgal commented
Commenting out would not mark the migration as migrated so when we uncomment it again so when a new migration file is added it will automatically duplicate this table. 
Instead we can add the --fake ie "python manage.py migrate --fake" , so that the migration is marked as migrated , and then we can remove the  --fake command for the subsequent deploys.

Thanks.

2024-12-17 16:45 UTC, DonnieBLT requested changes
Please check the tests.

2024-12-17 18:07 UTC, krrish-sehgal commented
@DonnieBLT sir , Good to merge 👍 .

2024-12-18 04:39 UTC, DonnieBLT approved these changes

2024-12-18 04:45 UTC, merged