Challenges leaderboard
OWASP-BLT/BLT pull request #3127
Opened 2024-12-18 18:49 UTC by krrish-sehgal

fixes #3126

2024-12-19 07:25 UTC, krrish-sehgal commented
@DonnieBLT sir, i have made the changes and attached a video, let me know of any other changes.

Thanks.

2024-12-19 14:14 UTC, krrish-sehgal commented
While there seems to be some overlap between the badge model and the challenge model , if in future we want to add badges for lets say , "Complete all the team challenges" , "Complete all weekly challenges in 3 consecutive weeks", wouldnt there be significant mismatch in the logic?

2024-12-19 14:53 UTC, krrish-sehgal commented
I believe then the this depends on the use case , if you plan to have badges associated with all the challenges , then combining the challenges and badge model would be good , but  if badges have multiple use cases beyond challenges then keeping them separate would be a better option , 

For teams i can modify the badge model to have a field like 
"  
AWARD_TARGETS = [
        ("individual", "Individual"),
        ("team", "Team"),
    ]
" 

and i can modify the UserBadge model to RecipientBadge model , that can link the badges to the users as well as teams depending on the badge . 

So like this we wont have to always have a badge for the challenge , but we will always have a challenge for a badge.

2024-12-19 15:21 UTC, krrish-sehgal commented
Sir, treating challenges that way would compromise the point system and leaderboard functionality. Currently, a challenge is marked as complete when team members collectively report 5 IPs, allowing the team to earn points and be ranked on the global leaderboard.

To maintain this system, I wanted to propose either of the following options:

1. Eliminate the whole global leaderboard system and keep the competition within team challenges only.
or i can do an addition of the within team challenges on this, like 
1. If a team challenge is completed, the team receives the badge, not the individual user.
2. If a within-team challenge is completed, two badges are awarded to the user: one for completing the individual challenge and another for completing the within-team challenge.

This way, we preserve the focus on team challenges while still recognizing individual efforts within teams.

2024-12-23 11:25 UTC, krrish-sehgal commented
> so I could report 5 ips for my team and earn two badges one for the team when all members find 5 ip and individual when I find 5

So , finally we want in team challenges to be like,
if all the user collectively complete the challenge and team entity is awarded a badge 
or 
i report 5ips and when other team members also report 5 ips , all the user entities of the team gets the badge not the team entity.

2025-01-19 01:10 UTC, DonnieBLT requested changes
please merge migrations

2025-01-24 03:56 UTC, krrish-sehgal commented
Apologies for the delay. 
I'll  fix it right away.

2025-01-24 06:34 UTC, krrish-sehgal commented
@DonnieBLT sir , Is it good to merge ?

2025-01-24 06:39 UTC, krrish-sehgal commented
The files changed when i ran pre-commit on them , most of the files  are same but adjusted by pre-commit, as the test case wasnt passing.

2025-01-24 07:42 UTC, krrish-sehgal commented
@DonnieBLT sir , i have reverted the changes , the pre-commit in the test is running on all the files , as it shows error in blt/middleware/iprestrict.py , whereas i havent changes the file in my commit .

2025-01-24 07:48 UTC, DonnieBLT submitted a review, later dismissed

2025-01-24 07:52 UTC, krrish-sehgal commented on comments/migrations/0007_remove_comment_issue_comment_content_type_and_more.py
No sir , this file out of the scope for this issue. pre-commit might have added this line , when i previously ran it.

2025-01-24 07:54 UTC, krrish-sehgal commented
@DonnieBLT Since you have approved , should i run pre-commit run --all-files ? so that it passes the test-case ?

2025-01-24 18:23 UTC, krrish-sehgal commented
@DonnieBLT sir , any more changes?

2025-01-26 10:28 UTC, DonnieBLT approved these changes

2025-01-26 10:28 UTC, merged