Prevent logging of requests that are blocked by middlewares
OWASP-BLT/BLT pull request #3135
Opened 2024-12-19 19:35 UTC by tsu-ki

Closes: https://github.com/OWASP-BLT/BLT/issues/3133

2024-12-21 04:22 UTC, DonnieBLT requested changes
Can this be done without another middleware file?

2024-12-21 09:02 UTC, tsu-ki commented
> Can this be done without another middleware file?

@DonnieBLT Sir, Initially I tried to define the class in `ip_restrict.py` file but due to circular import error during app registry initialization, I was getting this: 
`Since the app registry isn't fully loaded during the logging configuration phase, this results in the AppRegistryNotReady exception.`
So, to decouple the logging filter during initialization, I created a seperate filter module which doesn't cause the circular dependency problem.

2025-01-16 13:31 UTC, tsu-ki commented
@DonnieBLT sir, are there any changes to be made in this PR?

2025-01-22 10:40 UTC, tsu-ki commented
@DonnieBLT sir, is please review this PR and merge it, if there aren't changes to be made. thank you!

2025-02-17 22:35 UTC, closed without merging