Creating slack-bot for OWASP slack workspace
OWASP-BLT/BLT pull request #3145
Opened 2024-12-21 16:31 UTC by tsu-ki

Closes: https://github.com/OWASP-BLT/BLT/issues/3101

-Currently deploying the  in a private workspace to test the defined `/discover` command before integrating it into the official OWASP workspace.
- Defined https://api.github.com/orgs/OWASP/repos, as the endpoint for the slack bot to handle incoming requests. This endpoint will fetch the list of projects from OWASP's GitHub repository and return them to the user.

<img width="971" alt="Screenshot 2024-12-21 at 9 58 34 PM" src="https://github.com/user-attachments/assets/7d0d64dd-d9bd-48bc-9335-922087292311" />

2024-12-22 18:21 UTC, tsu-ki commented on website/views/core.py
> +def slack_discover(request):
@DonnieBLT Sure sir, I'll make the required corrections. I was testing the slack command in a test slack workspace and the commands weren't executing as intended, I'm correcting the script and will commit the changes once the commands work properly.

2025-01-01 16:57 UTC, DonnieBLT reviewed
lets make this /discover "keyword" so the keyword can be mern, python, gsoc and it will search all of the owasp projects from the site. and return a list of a link to the project wiki page and a brief description.

2025-01-01 16:57 UTC, DonnieBLT requested changes
lets make this /discover "keyword" so the keyword can be mern, python, gsoc and it will search all of the owasp projects from the site. and return a list of a link to the project wiki page and a brief description.

2025-01-01 19:07 UTC, tsu-ki commented
> lets make this /discover "keyword" so the keyword can be mern, python, gsoc and it will search all of the owasp projects from the site. and return a list of a link to the project wiki page and a brief description.

so sir should I include all OWASP associated project repositories and not just the ones associated with BLT? also, should I retain the github repository link and the issues feature where it's displaying latest features of selected repository? 
please do let me know about this

2025-01-03 20:18 UTC, tsu-ki commented
@DonnieBLT sir, please review the changes I've made as per your instructions. thank you!

https://github.com/user-attachments/assets/d7d1d76d-846b-488f-a081-5d00b078fbf7

2025-01-03 20:56 UTC, tsu-ki commented
> I meant the BLT website

Oh, I apologise for the misunderstanding. Sir, during CI/CD I'm getting the following error:
```
 File "/home/runner/work/BLT/BLT/website/views/slackbot.py", line 27, in <module>
    app = App(token=SLACK_BOT_TOKEN, signing_secret=SLACK_SIGNING_SECRET)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/blt-yuw0N2NF-py3.11/lib/python3.11/site-packages/slack_bolt/app/app.py", line 378, in __init__
    self._init_middleware_list(
  File "/home/runner/.cache/pypoetry/virtualenvs/blt-yuw0N2NF-py3.11/lib/python3.11/site-packages/slack_bolt/app/app.py", line 431, in _init_middleware_list
    raise BoltError(error_auth_test_failure(err.response))
slack_bolt.error.BoltError: `token` is invalid (auth.test result: {'ok': False, 'error': 'invalid_auth'})
```
It's related to not declaring `SLACK_BOT_TOKEN` as environment variables, please suggest on how can I resolve this?

suggest what changes can I make

2025-01-04 15:51 UTC, tsu-ki commented
@DonnieBLT sir, I was working on creating `/stats` slack commanded and will be committing changes in the same files as ones used in this PR. Please review and merge this PR, as then I can create draft PR for this issue: https://github.com/OWASP-BLT/BLT/issues/3172

2025-01-19 01:03 UTC, DonnieBLT submitted a review, later dismissed

2025-01-19 15:56 UTC, DonnieBLT approved these changes

2025-01-19 15:56 UTC, merged

2025-01-19 19:09 UTC, tsu-ki commented
@DonnieBLT sir, I was testing the slack bot but it wasn't responding as intended. Just wanted to confirm if you have added the environment variables mentioned in our slack conversation?