Add doughnut chart in stats
OWASP-BLT/BLT pull request #468
Opened 2017-08-10 16:22 UTC by jajodiaraghav

2017-08-10 20:04 UTC, goyal-sidd commented on website/templates/stats.html
> +    <br/>
there is a type here, it's <br/>.

2017-08-10 20:07 UTC, sid22 requested changes
Also sir, even after I corrected the` <br>` tag locally, the graph was still touching the footer. Maybe if a margin-bottom is added to this div or more than one `<br>` tag. 

The chart looks awesome either way though!

2017-08-11 04:28 UTC, jajodiaraghav commented
The issue is fixed! Replaced <br> with margin bottom :)

2017-08-11 07:33 UTC, sid22 approved these changes

2017-08-11 07:33 UTC, merged