new email templates
OWASP-BLT/BLT pull request #500
Opened 2017-08-31 18:36 UTC by goyal-sidd

The desktop view:-
![mail1](https://user-images.githubusercontent.com/17125030/29938959-fc2f9a06-8ea7-11e7-85fa-2f27eca08c10.png)

Mobile view:-
![mail3](https://user-images.githubusercontent.com/17125030/29939406-5ccf1b2e-8ea9-11e7-9537-f57d2c4231bd.png)

![mail2](https://user-images.githubusercontent.com/17125030/29938961-fc52ed80-8ea7-11e7-91ea-471e63f365a8.png)

2017-09-01 16:42 UTC, goyal-sidd commented
Changed the alignment of text to left align.

2017-09-04 18:18 UTC, fredfalcon requested changes
Looks good!  Thanks.  Can you please have the .html and .txt versions available?  Also can you add more info to the email, like the image of the bug and description, and any message text from users.

2017-09-05 03:10 UTC, fredfalcon approved these changes

2017-09-05 03:13 UTC, seanauriti commented
also please use this clear logo instead: 
![bughesitlogo](https://user-images.githubusercontent.com/7475382/30043660-b22ede7c-91c6-11e7-8404-a292885833d9.png)

2017-09-05 03:14 UTC, merged