wrong credentials error message showing
OWASP-BLT/BLT pull request #940
Opened 2022-08-27 18:40 UTC by AtmegaBuzz

Issue :  Wrong login credentials (Validation Message) not showing. #889 

prev it was not showing error message
![image](https://user-images.githubusercontent.com/68425016/187043836-8020fc12-1da2-47d4-a1d7-fb03571fcbf6.png)

2022-08-27 18:42 UTC, fredfalcon commented
I think the message is there we just need to show it.  We don’t need another view

2022-08-27 18:47 UTC, AtmegaBuzz commented
ok if thats the case then its not passing it in messages in the request. ill check

2022-08-31 08:29 UTC, AtmegaBuzz commented
@fredfalcon now error is showing without custom view 
![image](https://user-images.githubusercontent.com/68425016/187633046-66136d64-58b9-40cf-9db2-8ea451578855.png)

2022-08-31 09:51 UTC, fredfalcon requested changes
See comment

2022-08-31 09:51 UTC, fredfalcon commented on website/views.py
> +from allauth.account.views import LoginView,_ajax_response
Can remove this

2022-08-31 09:58 UTC, AtmegaBuzz commented on website/views.py
> +from allauth.account.views import LoginView,_ajax_response
ok

2022-08-31 09:58 UTC, AtmegaBuzz commented
@fredfalcon resolved

2022-08-31 10:04 UTC, fredfalcon approved these changes

2022-08-31 10:04 UTC, merged

2022-08-31 10:04 UTC, fredfalcon commented
Thank you!

2022-08-31 10:05 UTC, fredfalcon commented
If you link the issue to the pr it will close automatically https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue